version: "3.9"
services:
  postgres:
    image: postgres:13.3
    env_file:
     - .env
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G