version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_createx
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PostgresPassword
      POSTGRES_DB: createx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: