version: "3.9"
services:
  postgres:
    image: postgres:13.3
#    env_file:
#      - .env
    environment:
      POSTGRES_DB: "createx"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
    #  - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./db:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G          